### ISSUE TITLE
Traduccio

### ISSUE THREAD

**Issue by oolaria** [natxocc/CRC#1]
Fer traducció multiidioma per seleccionar l'idioma desitjat
(Botó desplegable y que la configuració es guardi al usuari)

**Comment by natxocc** [comment]
Ja s'ha generat el codi que farà que el CRC sigui multi Idioma.
Resta pendent:
* Quan es finalitzi el programa, fer la traducción al català i idiomes que es vulguin
* Que es personalitzi l'idioma per l'usuari i quedi enregistrat pel ell.

**Comment by oolaria** [comment]
Ja em passaras paraules i ho fem

Missatge enviat desdel meu IPhone

**Comment by natxocc** [comment]
Ja he fet el panell de traduccions. Fins ara está tot traduit a 2 idiomes, excepte els camps de la base de dades que son de 1 sol idioma per qüestions tècniques.
