### ISSUE TITLE
LIQUIDACIO SETMANAL

### ISSUE THREAD

**Issue by oolaria** [natxocc/CRC#22]
Com deiem ahir, la quidicació setmanal té que ser la foto de tots els rebuts cobrats durant aquella setmana (dilluns-diumenge) sigui per metàl.lic o bé per transf. banc.
Una condició més que ahir no et vaig dir es que si el rebut no ha vençut, no té que apareixer a la liquidació setmana fins que coincidexi amb la renovació.
Es a dir, no liquidem rebuts a companyia que encara no han renovat. A vegades tenim clients que abans de que es caduqui la pòl. ja venen a pagar, en canvi Reale no els afegeix a la liquidació fins que el rebut estigui vençut.

**Comment by natxocc** [comment]
Si DG>=DE ... DG <>SL
Si DG<DE ... DE <>SL

**Comment by oolaria** [comment]
![image](https://user-images.githubusercontent.com/47158007/52303295-e9bc3a80-298f-11e9-8485-9ae0ccdae9dd.png)
