### ISSUE TITLE
ESTADOS

### ISSUE THREAD

**Issue by oolaria** [natxocc/CRC#24]
AFEGIR DOS ESTATS MÉS:

COBRADOS BESTRETA METALICO Y TRANSF.

TENIR CONTROL VISUAL DE LES CUATRE CAIXES,   OFICINA+BANC+BESTRETES+PROVISIONALS

PODER FER MOVIMENTS MANUALS:

DATA + USUARI + ORIGEN + DESTI + MOVIMENT (LIQUIDACIO, BESTRETA, REBUT) + IMPORT

**Comment by natxocc** [comment]
Per els provisionals també hem de ficar 2 estats mes?
PROVISIONAL METALICO?
PROVISIONAL TRANSFERENCIA?

O sempre que es fa un provisional es fa en metàlic?

**Comment by oolaria** [comment]
Si, bestreta potser metalic i transf

Missatge enviat desdel meu IPhone

**Comment by natxocc** [comment]
Vull dir, tenim:

**Cobrat 100%:**
* COBRADO Metalic
* COBRADO Transferencia
* COBRADO Banc
* COBRADO Tarja

**Bestretes:**
* COBRADO Metalic
* COBRADO Transferencia

**Provisionals** (els seguros que encara no son complerts, que es demanen per quan es compra un cotxe nou i aixó):
* COBRADO Metalic ??
* COBRADO Transferencia???
* O només en metàlic son aquestos casos?
* O treiem el concepte de PROVISIONALS?

**Comment by oolaria** [comment]
En tenim que parlar

Missatge enviat desdel meu IPhone

**Comment by natxocc** [comment]
Ja he fet un prototip de gestio.
