### ISSUE TITLE
Llistat de gestio de rebuts

### ISSUE THREAD

**Issue by oolaria** [natxocc/CRC#3]
Al desplegar, volem que es vegi l'historial per client

**Comment by natxocc** [comment]
Permet filtrar per 3 opcions:

Per Client (per defecte) Historial de client
Per Rebut: Historial per rebut
Per pòlissa: Historial per pòlissa

![image](https://user-images.githubusercontent.com/1172351/52492013-aac4f980-2bc8-11e9-9f50-9190e2dac8b2.png)
